@base_url = http://localhost:8080/api/user

# FINDBYEMAIL happy path
GET {{base_url}}/email/peaveybryan03@gmail.com HTTP/1.1

###

# FINDBYEMAIL user not found
GET {{base_url}}/email/notinrepo@gmail.com HTTP/1.1

###

# FINDBYNAME happy path
GET {{base_url}}/name/bryanpeavey HTTP/1.1

###

# FINDBYNAME user not found
GET {{base_url}}/name/notinrepo HTTP/1.1

###

# AUTHENTICATE happy path
POST {{base_url}}/login HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "bryanpeavey",
    "email": "peaveybryan03@gmail.com",
    "password": "janetluvr"
}

###

# AUTHENTICATE user does not exist
POST {{base_url}}/login HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "bryanpeavey",
    "email": "notinrepo@gmail.com",
    "password": "janetluvr"
}

###

# AUTHENTICATE incorrect password
POST {{base_url}}/login HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "bryanpeavey",
    "email": "peaveybryan03@gmail.com",
    "password": "incorrect"
}

###

# CREATE happy path
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "name",
    "email": "valid@gmail.com",
    "password": "password"
}

###

# CREATE blank name
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "email": "email@gmail.com",
    "password": "password"
}

###

# CREATE blank email
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "name",
    "email": "",
    "password": "password"
}

###

# CREATE blank password
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "name",
    "email": "email@email.com",
    "password": ""
}

###

# CREATE duplicate name
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "bryanpeavey",
    "email": "nonduplicate@gmail.com",
    "password": "password"
}

###

# CREATE duplicate email
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "non-duplicate",
    "email": "peaveybryan03@gmail.com",
    "password": "password"
}